///////////////////////////////////////////////////////////////////////
NOTE TO WRITERS:
This is a list of software required in addition to the TCK and the RI.
For many Java EE APIs, the Java EE RI will be required, as described below.
For standalone technologies, no other software may be required, and the
below line can be removed.

This is used in intro.adoc in section 1.3 and install.adoc in section 3.2.
///////////////////////////////////////////////////////////////////////

* Jakarta EE {JakartaEEVersion} CI such as Eclipse GlassFish 6.1 or, at a minimum, a Web server with a Servlet container
