///////////////////////////////////////////////////////////////////////
NOTE TO WRITERS:
This is included at the tail end of the Title page.
The following section should be customized for the technology.
This is provided to allow each technology to customize legacy acronym names
that are used in this TCK. 
Be sure to customize LegacyAcronym in attributes.conf
Add additional lines as needed for acronyms found in your TCK user guide.
///////////////////////////////////////////////////////////////////////

References in this document to {LegacyAcronym} refer to the {TechnologyFullName} unless otherwise noted.
