////
*******************************************************************
* Copyright (c) 2019 Eclipse Foundation
*
* This specification document is made available under the terms
* of the Eclipse Foundation Specification License v1.0, which is
* available at https://www.eclipse.org/legal/efsl.php.
*******************************************************************
////

[[entity_providers]]
=== Entity Providers

Entity providers supply mapping services between representations and
their associated Java types. Entity providers come in two flavors:
`MessageBodyReader` and `MessageBodyWriter` described below.

[[message_body_reader]]
==== Message Body Reader

The `MessageBodyReader` interface defines the contract between the
JAX-RS runtime and components that provide mapping services from
representations to a corresponding Java type. A class wishing to provide
such a service implements the `MessageBodyReader` interface and may be
annotated with `@Provider` for automatic discovery.

The following describes the logicalfootnote:[Implementations are free to
optimize their processing provided the results are equivalent to those
that would be obtained if these steps are followed.] steps taken by a
JAX-RS implementation when mapping a message entity body to a Java
method parameter:

1.  Obtain the media type of the request. If the request does not
contain a `Content-Type` header then use `application/octet-stream`.
2.  Identify the Java type of the parameter whose value will be mapped
from the entity body. <<mapping_requests_to_java_methods>>
describes how the Java method is chosen.
3.  Select the set of `MessageBodyReader` classes that support the media
type of the request, see <<declaring_provider_capabilities>>.
4.  Iterate through the selected
`MessageBodyReader` classes and, utilizing the `isReadable` method of
each, choose a `MessageBodyReader` provider that supports the desired
Java type.
5.  If step 4 locates one or more suitable
`MessageBodyReader`’s then select the one with the highest priority as
described in <<provider_priorities>> and use its `readFrom` method
to map the entity body to the desired Java type.
6.  Otherwise, the server runtime MUST generate a
`NotSupportedException` (415 status) and no entity (to be processed as
described in <<method_exc>>) and the client runtime MUST generate
an instance of `ProcessingException`.

See <<exceptions_providers>> for more information on handling
exceptions thrown in `MessageBodyReader.readFrom`.

[[message_body_writer]]
==== Message Body Writer

The `MessageBodyWriter` interface defines the contract between the
JAX-RS runtime and components that provide mapping services from a Java
type to a representation. A class wishing to provide such a service
implements the `MessageBodyWriter` interface and may be annotated with
`@Provider` for automatic discovery.

The following describes the logical steps taken by a
JAX-RS implementation when mapping a return value to a message entity
body:

1.  Obtain the object that will be mapped to the message entity body.
For a return type of `Response` or subclasses, the object is the value
of the `entity` property, for other return types it is the returned
object.
2.  Determine the media type of the response, see Section
[determine_response_type].
3.  Select the set of `MessageBodyWriter` providers that support (see
<<declaring_provider_capabilities>>) the object and media type of
the message entity body.
4.  Sort the selected `MessageBodyWriter` providers with a
primary key of generic type where providers whose generic type is the
nearest superclass of the object class are sorted first and a secondary
key of media type (see Section [declaring_provider_capabilities]).
5.  Iterate through the sorted
`MessageBodyWriter` providers and, utilizing the `isWriteable` method of
each, choose an `MessageBodyWriter` that supports the object that will
be mapped to the entity body.
6.  If step 5 locates one or more suitable
`MessageBodyWriter`’s that are equal with respect to the sorting in step
4, then select the one with the highest priority as described
in <<provider_priorities>> and use its `writeTo` method to map the
entity body to the desired Java type.
7.  Otherwise, the server runtime MUST generate a generate an
`InternalServerErrorException`, a subclass of
`WebApplicationException` with its status set to 500, and no entity (to
be processed as described in <<method_exc>>) and the client
runtime MUST generate a `ProcessingException`.

Experience gained in the field has resulted in the reversal of the
sorting keys in step 4 in this specification. This represents
a backward incompatible change with respect to JAX-RS 1.X.
Implementations of this specification are REQUIRED to provide a backward
compatible flag for those applications that rely on the previous
ordering. The mechanism defined to enable this flag is implementation
dependent.

See <<exceptions_providers>> for more information on handling
exceptions thrown in `MessageBodyWriter.write`.

[[declaring_provider_capabilities]]
==== Declaring Media Type Capabilities

Message body readers and writers MAY restrict the media types they
support using the `@Consumes` and `@Produces` annotations respectively.
The absence of these annotations is equivalent to their inclusion with
media type (/*), i.e. absence implies that any media type is supported.
An implementation MUST NOT use an entity provider for a media type that
is not supported by that provider.

When choosing an entity provider an implementation sorts the available
providers according to the media types they declare support for. Sorting
of media types follows the general rule: x/y latexmath:[$<$] x/*
latexmath:[$<$] */*, i.e. a provider that explicitly lists a media types
is sorted before a provider that lists */*.

[[standard_entity_providers]]
==== Standard Entity Providers

An implementation MUST include pre-packaged `MessageBodyReader` and
`MessageBodyWriter` implementations for the following Java and media
type combinations:

`byte[]`::
  All media types (`/*`).
`java.lang.String`::
  All media types (`/*`).
`java.io.InputStream`::
  All media types (`/*`).
`java.io.Reader`::
  All media types (`/*`).
`java.io.File`::
  All media types (`/*`).
`jakarta.activation.DataSource`::
  All media types (`/*`).
`jakarta.xml.transform.Source`::
  XML types (`text/xml`, `application/xml` and media types of the form
  `application/*+xml`).
`jakarta.xml.bind.JAXBElement` and application-supplied JAXB classes::
  XML types (`text/xml` and `application/xml` and media types of the
  form `application/*+xml`).
`MultivaluedMap<String,String>`::
  Form content (`application/x-www-form-urlencoded`).
`StreamingOutput`::
  All media types (`/*`), `MessageBodyWriter` only.
`java.lang.Boolean`, `java.lang.Character`, `java.lang.Number`::
  Only for `text/plain`. Corresponding primitive types supported via
  boxing/unboxing conversion.

Depending on the environment, the list of standard entity providers MUST
also include those for JSON. For more information about these providers
see <<jsonp>> and <<jsonb>>.

When reading zero-length message entities all pre-packaged
`MessageBodyReader` implementations, except the JAXB one and those for
the (boxed) primitive types above, MUST create a corresponding Java
object that represents zero-length data. The pre-packaged JAXB and the
pre-packaged primitive type `MessageBodyReader` implementations MUST
throw a `NoContentException` for zero-length message entities.

When a `NoContentException` is thrown while reading a server request
entity from a `MessageBodyReader` it MUST be translated by the server
runtime into a `BadRequestException` wrapping the original
`NoContentException` and re-thrown to be processed by any registered
exception mappers.

The implementation-supplied entity provider(s) for
`jakarta.xml.bind.JAXBElement` and application-supplied JAXB classes MUST
use `JAXBContext` instances provided by application-supplied context
resolvers, see <<contextprovider>>. If an application does not
supply a `JAXBContext` for a particular type, the
implementation-supplied entity provider MUST use its own default context
instead.

When writing responses, implementations SHOULD respect
application-supplied character set metadata and SHOULD use UTF-8 if a
character set is not specified by the application or if the application
specifies a character set that is unsupported.

An implementation MUST support application-provided entity providers and
MUST use those in preference to its own pre-packaged providers when
either could handle the same request. More precisely, step 4
in <<message_body_reader>> and step 5 in
<<message_body_writer>> MUST prefer application-provided over pre-packaged
entity providers.

[[transfer_encoding]]
==== Transfer Encoding

Transfer encoding for inbound data is handled by a component of the
container or the JAX-RS runtime. `MessageBodyReader` providers always
operate on the decoded HTTP entity body rather than directly on the HTTP
message body.

A JAX-RS runtime or container MAY transfer encode outbound data or this
MAY be done by application code.

[[content-encoding]]
==== Content Encoding

Content encoding is the responsibility of the application.
Application-supplied entity providers MAY perform such encoding and
manipulate the HTTP headers accordingly.
