////
*******************************************************************
* Copyright (c) 2019 Eclipse Foundation
*
* This specification document is made available under the terms
* of the Eclipse Foundation Specification License v1.0, which is
* available at https://www.eclipse.org/legal/efsl.php.
*******************************************************************
////

[[exceptionmapper]]
=== Exception Mapping Providers

Exception mapping providers map a checked or runtime exception to an
instance of `Response`. An exception mapping provider implements the
`ExceptionMapper<T>` interface and may be annotated with `@Provider` for
automatic discovery.

When a resource class or provider method throws an exception,
the matching provider is used to
obtain a `Response` instance. The resulting `Response` is processed as
if a web resource method had returned the `Response`, see
<<resource_method_return>>. In particular, a mapped `Response` MUST be
processed using the ContainerResponse filter chain defined in
Chapter <<filters_and_interceptors>>.

When choosing an exception mapping provider to map an exception, an
implementation MUST use the provider whose generic type is the nearest
superclass of the exception. If two or more exception providers are
applicable, the one with the highest priority MUST be chosen as
described in <<provider_priorities>>.

A JAX-RS implementation MUST include a default exception mapping provider
that implements ExceptionMapper<Throwable> and which SHOULD
set the response status to 500.

When the default exception mapping provider handles a WebApplicationException, it MUST
return the embedded Response, and it MUST respect the status code in the Response.

To avoid a potentially infinite loop, a single exception mapper must be
used during the processing of a request and its corresponding response.
JAX-RS implementations MUST NOT attempt to map exceptions thrown while
processing a response previously mapped from an exception. Instead, this
exception MUST be processed as described in steps 3 and
4 in <<method_exc>>.

Note that exception mapping providers are _not_ supported as part of the
Client API.
