////
*******************************************************************
* Copyright (c) 2019 Eclipse Foundation
*
* This specification document is made available under the terms
* of the Eclipse Foundation Specification License v1.0, which is
* available at https://www.eclipse.org/legal/efsl.php.
*******************************************************************
////

[[providers]]
== Providers

Providers in JAX-RS are responsible for various cross-cutting concerns
such as filtering requests, converting representations into Java
objects, mapping exceptions to responses, etc. A provider can be either
_pre-packaged_ in the JAX-RS runtime or supplied by an application. All
_application-supplied_ providers implement interfaces in the JAX-RS API
and MAY be annotated with `@Provider` for automatic discovery purposes;
the integration of pre-packaged providers into the JAX-RS runtime is
implementation dependent.

This chapter introduces some of the basic JAX-RS providers; other
providers are introduced in Chapter <<client_api>> and Chapter
<<filters_and_interceptors>>.

include::_lifecycle_and_environment.adoc[]

include::_entity_providers.adoc[]

include::_contextprovider.adoc[]

include::_exceptionmapper.adoc[]

include::_exceptions_providers.adoc[]
