////
*******************************************************************
* Copyright (c) 2019 Eclipse Foundation
*
* This specification document is made available under the terms
* of the Eclipse Foundation Specification License v1.0, which is
* available at https://www.eclipse.org/legal/efsl.php.
*******************************************************************
////

[[executor_services]]
=== Executor Services

Executor services can be used to submit asynchronous tasks for
execution. JAX-RS applications can specify executor services while
building a `Client` instance. Two methods are provided in
`ClientBuilder` for this purpose, namely, `executorService` and
`scheduledExecutorService`.

In an environment that supports Jakarta Concurrency
<<bib13>>, such as full Jakarta EE platform products, implementations MUST use
`ManagedExecutorService` and `ManagedScheduledExecutorService`,
respectively. The reader is referred to the Javadoc of `ClientBuilder`
for more information about executor services.
