////
*******************************************************************
* Copyright (c) 2019 Eclipse Foundation
*
* This specification document is made available under the terms
* of the Eclipse Foundation Specification License v1.0, which is
* available at https://www.eclipse.org/legal/efsl.php.
*******************************************************************
////

[[resource_access]]
=== Resource Access

A Web resource can be accessed using a fluent API in which method
invocations are chained to build and ultimately submit an HTTP request.
The following example gets a `text/plain` representation of the resource
identified by `http://example.org/hello`:

[source,java]
----
Client client = ClientBuilder.newClient();
Response res = client.target("http://example.org/hello")
    .request("text/plain").get();
----

Conceptually, the steps required to submit a request are the following:
(i) obtain an instance of `Client` (ii) create a `WebTarget` (iii)
create a request from the `WebTarget` and (iv) submit a request or get a
prepared `Invocation` for later submission. See Section [invocations]
for more information on using `Invocation`.

Method chaining is not limited to the example shown above. A request can
be further specified by setting headers, cookies, query parameters, etc.
For example:

[source,java]
----
Response res = client.target("http://example.org/hello")
    .queryParam("MyParam","...")
    .request("text/plain")
    .header("MyHeader", "...")
    .get();
----

See the Javadoc for the classes in the `jakarta.ws.rs.client` package for
more information.
