////
*******************************************************************
* Copyright (c) 2019 Eclipse Foundation
*
* This specification document is made available under the terms
* of the Eclipse Foundation Specification License v1.0, which is
* available at https://www.eclipse.org/legal/efsl.php.
*******************************************************************
////

[[typed-entities]]
=== Typed Entities

The response to a request is not limited to be of type `Response`. The
following example upgrades the status of customer number 123 to "gold
status" by first obtaining an entity of type `Customer` and then
posting that entity to a different URI:

[source,java]
----
Customer c = client.target("http://examples.org/customers/123")
.request("application/xml").get(Customer.class);
String newId = client.target("http://examples.org/gold-customers/")
.request().post(xml(c), String.class);
----

Note the use of the _variant_ `xml()` in the call to `post`. The class
`jakarta.ws.rs.client.Entity` defines variants for the most popular media
types used in JAX-RS applications.

In the example above, just like in the Server API,
JAX-RS implementations are REQUIRED to use entity providers to map a
representation of type `application/xml` to an instance of `Customer`
and vice versa. See <<standard_entity_providers>> for a list of
entity providers that MUST be supported by all JAX-RS implementations.
