[[runtimedelegate]]
== Runtime Delegate

`RuntimeDelegate` is an abstract factory class that provides various
methods for the creation of objects that implement JAX-RS APIs. These
methods are designed for use by other JAX-RS API classes and are not
intended to be called directly by applications. `RuntimeDelegate` allows
the standard JAX-RS API classes to use different JAX-RS implementations
without any code changes.

An implementation of JAX-RS MUST provide a concrete subclass of
`RuntimeDelegate`. Using the supplied `RuntimeDelegate` this can be
provided to JAX-RS in one of two ways:

1.  An instance of `RuntimeDelegate` can be instantiated and injected
using its static method `setInstance`. In this case the implementation
is responsible for creating the instance; this option is intended for
use with implementations based on IoC frameworks.
2.  The class to be used can be configured, see <<rdconfig>>. In
this case JAX-RS is responsible for instantiating an instance of the
class and the configured class MUST have a public constructor which
takes no arguments.

Note that an implementation MAY supply an alternate implementation of
the `RuntimeDelegate` API class (provided it passes the TCK signature
test and behaves according to the specification) that supports alternate
means of locating a concrete subclass.

A JAX-RS implementation may rely on a particular implementation of
`RuntimeDelegate` being used – applications SHOULD NOT override the
supplied `RuntimeDelegate` instance with an application-supplied
alternative and doing so may cause unexpected problems.

[[rdconfig]]
=== Configuration

If not supplied by injection, the supplied `RuntimeDelegate` API class
obtains the concrete implementation class using the following algorithm.
The steps listed below are performed in sequence and, at each step, at
most one candidate implementation class name will be produced. The
implementation will then attempt to load the class with the given class
name using the current context class loader or, missing one, the
`java.lang.Class.forName(String)` method. As soon as a step results in
an implementation class being successfully loaded, the algorithm
terminates.

1.  Use the Java SE class `java.util.ServiceLoader` to attempt to load
an implementation from
`META-INF/services/javax.ws.rs.ext.RuntimeDelegate`. Note that this may
require more than one call to method
`ServiceLoader.load(Class, ClassLoader)` in order to try both the
context class loader and the current class loader as explained
above.footnote:[Earlier versions of JAX-RS did not mandate the use
`ServiceLoader`. This backward-compatible change that started in
JAX-RS 2.1 is to ensure forward compatibility with the Java SE 9 module
system.]
2.  If the `${java.home}/lib/jaxrs.properties` file exists and it is
readable by the `java.util.Properties.load(InputStream)` method and it
contains an entry whose key is `javax.ws.rs.ext.RuntimeDelegate`, then
the value of that entry is used as the name of the implementation class.
3.  If a system property with the name `javax.ws.rs.ext.RuntimeDelegate`
is defined, then its value is used as the name of the implementation
class.
4.  Finally, a default implementation class name is used.
