[[sse]]
== Server-Sent Events

[[sse_introduction]]
=== Introduction

Server-sent events (SSE) is a specification originally introduced as
part of HTML5 by the W3C, but is currently maintained by the WHATWG
<<bib17>>. It provides a way to establish a one-way
channel from a server to a client. The connection is long running: it is
re-used for multiple events sent from the server, yet it is still based
on the HTTP protocol. Clients request the opening of an SSE connection
by using the special media type `text/event-stream` in the `Accept`
header.

Events are structured and contain several fields, namely, `event`,
`data`, `id`, `retry` and `comment`. SSE is a messaging protocol where
the `event` field corresponds to a topic, and where the `id` field can
be used to validate event order and guarantee continuity. If a
connection is interrupted for any reason, the `id` can be sent in a
request header for a server to re-play past events —although this is an
optional behavior that may not be supported by all implementations.
Event payloads are conveyed in the `data` field and must be in text
format; `retry` is used to control re-connects and finally `comment` is
a general purpose field that can also be used to keep connections alive.

[[sse_client_api]]
=== Client API

The JAX-RS client API for SSE was inspired by the corresponding
JavaScript API in HTML5, but with changes that originate from the use of
a different language. The entry point to the client API is the type
`SseEventSource`, which provides a fluent builder similarly to other
classes in the JAX-RS API. An `SseEventSource` is constructed from a
`WebTarget` that is already configured with a resource location;
`SseEventSource` does not duplicate any functionality in `WebTarget` and
only adds the necessary logic for SSE.

The following example shows how to open an SSE connection and read some
messages for a little while:

[source,java,numbered]
-------------
WebTarget target = client.target("http://...");
try (SseEventSource source = SseEventSource.target(target).build()) {
    source.register(System.out::println);
    source.open();
    Thread.sleep(500); // Consume events for just 500 ms
} catch (InterruptedException e) {
    // falls through
}
-------------

As seen in this example, an `SseEventSource` implements `AutoCloseable`.
Before opening the source, the client registers an event consumer that
simply prints each event. Additional handlers for other life-cycle
events such as `onComplete` and `onError` are also supported, but for
simplicity only `onEvent` is shown in the example above.

[[sse_server_api]]
=== Server API

The JAX-RS SSE server API is used to accept connections and send events
to one or more clients. A resource method that injects an `SseEventSink`
and produces the media type `text/event-stream` is an SSE resource
method.

The following example accepts SSE connections and uses an executor
thread to send 3 events before closing the connection:

[source,java,numbered]
-------------
@GET
@Path("eventStream")
@Produces(MediaType.SERVER_SENT_EVENTS)
public void eventStream(@Context SseEventSink eventSink,
                        @Context Sse sse) {
    executor.execute(() -> {
        try (SseEventSink sink = eventSink) {
            eventSink.send(sse.newEvent("event1"));
            eventSink.send(sse.newEvent("event2"));
            eventSink.send(sse.newEvent("event3"));
        }
    });
}
-------------

SSE resource methods follow a similar pattern to those for asynchronous
processing (see <<introduction_async>>) in that the object
representing the incoming connection, in this case `SseEventSink`, is
injected into the resource method.

The example above also injects the `Sse` type which provides factory
methods for events and broadcasters. See <<sse_broadcasting>> for
more information about broadcasting. Note that, just like
`SseEventSource`, the interface `SseEventSink` is also auto-closeable,
hence the use of the _try-with-resources_ statement above.

Method `send` on `SseEventSink` returns a `CompletionStage<?>` as a way
to provide a _handle_ to the action of asynchronously sending a message
to a client.

[[sse_broadcasting]]
=== Broadcasting

Applications may need to send events to multiple clients simultaneously.
This action is called _broadcasting_ in JAX-RS. Multiple
`SseEventSink`’s can be registered on a single `SseBroadcaster`.

A broadcaster can only be created by calling method `newBroadcaster` on
the injected `Sse` instance. The life-cycle and scope of an
`SseBroadcaster` is fully controlled by applications and not the
JAX-RS runtime. The following example shows the use of broadcasters,
note the `@Singleton` annotation on the resource class:

[source,java,numbered]
-------------
@Path("/")
@Singleton
public class SseResource {

    @Context
    private Sse sse;

    private volatile SseBroadcaster sseBroadcaster;

    @PostConstruct
    public init() {
        this.sseBroadcaster = sse.newBroadcaster();
    }

    @GET
    @Path("register")
    @Produces(MediaType.SERVER_SENT_EVENTS)
    public void register(@Context SseEventSink eventSink) {
        eventSink.send(sse.newEvent("welcome!"));
        sseBroadcaster.register(eventSink);
    }

    @POST
    @Path("broadcast")
    @Consumes(MediaType.MULTIPART_FORM_DATA)
    public void broadcast(@FormParam("event") String event) {
        sseBroadcaster.broadcast(sse.newEvent(event));
    }
}
-------------

The `register` method on a broadcaster is used to add a new
`SseEventSink`; the `broadcast` method is used to send an SSE event to
all registered consumers.

[[sse_pipeline]]
=== Processing Pipeline

Connections from SSE clients are represented by injectable instances of
`SseEventSink`. There are some similarities between SSE and asynchronous
processing (see Chapter <<asynchronous_processing>>). Asynchronous
responses can be resumed at most once while an `SseEventSink` can be
used multiple times to stream individual events.

For compatibility purposes, implementations MUST initiate processing of
an SSE response when either the first message is sent or when the
resource method returns, whichever happens first. The initial SSE
response, which may only include the HTTP headers, is processed using
the standard JAX-RS pipeline as described in Appendix
<<processing_pipeline>>. Each subsequent SSE event may include a different
payload and thus require the use of a specific message body writer. Note
that since this use case differs slightly from the normal
JAX-RS pipeline, implementations SHOULD NOT call entity interceptors on
each individual event.footnote:[As a matter of fact, there is no API to
bind entity interceptors to individual SSE events.]

[[sse_environment]]
=== Environment

The `SseEventSource` class uses the existing JAX-RS mechanism based on
`RuntimeDelegate` to find an implementation using the service name
`javax.ws.rs.sse.SseEventSource.Builder`. The majority of types in the
`javax.ws.rs.sse` are thread safe; the reader is referred to the Javadoc
for more information on thread safety.
