////
*******************************************************************
* Copyright (c) 2019 Eclipse Foundation
*
* This specification document is made available under the terms
* of the Eclipse Foundation Specification License v1.0, which is
* available at https://www.eclipse.org/legal/efsl.php.
*******************************************************************
////

[[acks]]
=== Acknowledgements

During the course of this JSR we received great contributions and
suggestions from many individuals. Special thanks to Marek Potociar and
Michal Gajdos. Also Gunnar Morling, Ondrej Mihalyi, Arjan Tijms,
Guillermo Gonzales de Aguero, Christian Kaltepoth and many, many others.
Last but not least to the JSR 370 Expert Group for all their
contributions.

During the course of JSR 339 we received many excellent suggestions.
Special thanks to Martin Matula, Gerard Davison, Jakub Podlesak and
Pavel Bucek from Oracle as well as Pete Muir and Emmanuel Bernard from
Red Hat. Also to Gunnar Morling and Ron Sigal (Red Hat) for their
suggestions on how to improve resource validation, and to Mattias
Arthursson for his insights on hypermedia.

During the course of JSR 311 we received many excellent suggestions on
the JSR and Jersey (RI) mailing lists, thanks in particular to James
Manger (Telstra) and Reto Bachmann-Gmür (Trialox) for their
contributions. The following individuals (all Sun Microsystems at the
time) have also made invaluable technical contributions: Roberto
Chinnici, Dianne Jiao (TCK), Ron Monzillo, Rajiv Mordani, Eduardo
Pelegri-Llopart, Jakub Podlesak (RI) and Bill Shannon.

The `GenericEntity` class was inspired by the Google Guice `TypeLiteral`
class. Our thanks to Bob Lee and Google for donating this class to
JAX-RS.
