////
*******************************************************************
* Copyright (c) 2019, 2023 Eclipse Foundation
*
* This specification document is made available under the terms
* of the Eclipse Foundation Specification License v1.0, which is
* available at https://www.eclipse.org/legal/efsl.php.
*******************************************************************
////

[[status]]
=== Status

This is the M1 release of version 4.0. The issue tracking system for
this release can be found at:

https://github.com/jakartaee/rest/issues

The corresponding Javadocs can be found online at:

https://jakarta.ee/specifications/restful-ws/4.0/apidocs/

A compatible implementation can be obtained from:

https://eclipse-ee4j.github.io/jersey/

The project team seeks feedback from the community on any aspect of this
specification, please send comments to:

jaxrs-dev@eclipse.org

[[context-injection]]
==== @Context Injection Removed

As part of an effort to better align with https://jakarta.ee/specifications/cdi/[Jakarta CDI],
support for `@Context` injection and related types such as `ContextResolver` have been removed.
All injection tasks have been delegated to Jakarta CDI for a better integration into the
https://jakarta.ee/[Jakarta EE] ecosystem.
