////
*******************************************************************
* Copyright (c) 2019, 2024 Eclipse Foundation
*
* This specification document is made available under the terms
* of the Eclipse Foundation Specification License v1.0, which is
* available at https://www.eclipse.org/legal/efsl.php.
*******************************************************************
////

[[status]]
=== Status

This is the final release of version 3.2. The issue tracking system for
this release can be found at:

https://github.com/jakartaee/rest/issues

The corresponding Javadocs can be found online at:

https://jakarta.ee/specifications/restful-ws/4.0/apidocs/

A compatible implementation can be obtained from:

https://eclipse-ee4j.github.io/jersey/

The project team seeks feedback from the community on any aspect of this
specification, please send comments to:

jaxrs-dev@eclipse.org

[[context-injection]]
==== Support for @Context Injection

As part of an effort to better align with https://jakarta.ee/specifications/cdi/[Jakarta CDI],
future versions of this API will no longer support `@Context` injection and related types such as
`ContextResolver`. As much as possible, all injection tasks will be delegated to
Jakarta CDI for a better integration into the https://jakarta.ee/[Jakarta EE] ecosystem.
