////
*******************************************************************
* Copyright (c) 2019 Eclipse Foundation
*
* This specification document is made available under the terms
* of the Eclipse Foundation Specification License v1.0, which is
* available at https://www.eclipse.org/legal/efsl.php.
*******************************************************************
////

[[introduction_async]]
=== Introduction

Asynchronous processing is a technique that enables a better and more
efficient use of processing threads. On the client side, a thread that
issues a request may also be responsible for updating a UI component; if
that thread is blocked waiting for a response, the user’s perceived
performance of the application will suffer. Similarly, on the server
side, a thread that is processing a request should avoid blocking while
waiting for an external event to complete so that other requests
arriving to the server during that period of time can be
attendedfootnote:[The maximum number of request threads is typically set
by the administrator; if that upper bound is reached, subsequent
requests will be rejected.].
