////
*******************************************************************
* Copyright (c) 2019 Eclipse Foundation
*
* This specification document is made available under the terms
* of the Eclipse Foundation Specification License v1.0, which is
* available at https://www.eclipse.org/legal/efsl.php.
*******************************************************************
////

[[server_api]]
=== Server API

[[async_response]]
==== AsyncResponse

Synchronous processing requires a resource method to produce a response
upon returning control back to the JAX-RS implementation. Asynchronous
processing enables a resource method to inform the JAX-RS implementation
that a response is not readily available upon return but will be
produced at a future time. This can be accomplished by first
_suspending_ and later _resuming_ the client connection on which the
request was received.

Let us illustrate these concepts via an example:

[source,java]
----
@Path("/async/longRunning")
public class MyResource {

    @GET
    public void longRunningOp(@Suspended final AsyncResponse ar) {
        executor.submit(
            new Runnable() {
                public void run() {
                    executeLongRunningOp();
                    ar.resume("Hello async world!");
                }
            });
    }
    ...
}
----

A resource method that elects to produce a response asynchronously must
inject as a method parameter an instance of the class `AsyncResponse`
using the special annotation `@Suspended`. In the example above, the
method `longRunningOp` is called upon receiving a `GET` request. Rather
than producing a response immediately, this method forks a (non-request)
thread to execute a long running operation and returns immediately. Once
the execution of the long running operation is complete, the connection
is resumed and the response returned by calling `resume` on the injected
instance of `AsyncResponse`.

For more information on executors, concurrency and thread management in
a Jakarta EE environment, the reader is referred to Jakarta Concurrency
Specification <<bib13>>. For more information about
executors in the JAX-RS Client API see <<executor_services>>.

[[timeouts_and_callbacks]]
===== Timeouts and Callbacks

A timeout value can be specified when suspending a connection to avoid
waiting for a response indefinitely. The default unit is milliseconds,
but any unit of type `java.util.concurrent.TimeUnit` can be used. The
following example sets a timeout of 15 seconds and registers an instance
of `TimeoutHandler` in case the timeout is reached before the connection
is resumed.

[source,java]
----
@GET
public void longRunningOp(@Suspended final AsyncResponse ar) {
    // Register handler and set timeout
    ar.setTimeoutHandler(new TimeoutHandler() {
        public void handleTimeout(AsyncResponse ar) {
            ar.resume(Response.status(SERVICE_UNAVAILABLE).entity(
                "Operation timed out -- please try again").build());
            }
    });
    ar.setTimeout(15, SECONDS);

    // Execute long running operation in new thread
    executor.execute(
        new Runnable() {
            public void run() {
                executeLongRunningOp();
                ar.resume("Hello async world!");
            }
        });
}
----

JAX-RS implementations are REQUIRED to generate a
`ServiceUnavailableException`, a subclass of
`WebApplicationException` with its status set to 503, if the timeout
value is reached and no timeout handler is registered. The exception
MUST be processed as described in <<method_exc>>. If a registered
timeout handler resets the timeout value or resumes the connection and
returns a response, JAX-RS implementations MUST NOT generate an
exception.

It is also possible to register callbacks on an instance of
`AsyncResponse` in order to listen for processing completion
(`CompletionCallback`) and connection termination (`ConnectionCallback`)
events. See Javadoc for `AsyncResponse` for more information on how to
register these callbacks. Note that support for `ConnectionCallback` is
OPTIONAL.

[[completionstage]]
==== CompletionStage

An alternative approach to the injection of `AsyncResponse` is for a
resource method to return an instance of `CompletionStage<T>` as an
indication to the underlying JAX-RS implementation that asynchronous
processing is enabled. The example from <<async_response>> can be
re-written using `CompletionStage` as follows:

[source,java]
----
@Path("/async/longRunning")
public class MyResource {

    @GET
    public CompletionStage<String> longRunningOp() {
        CompletableFuture<String> cs = new CompletableFuture<>();
        executor.submit(
            new Runnable() {
                public void run() {
                    executeLongRunningOp();
                    cs.complete("Hello async world!");
                }
            });
        return cs;
    }
    ...
}
----

In this example, a `CompletableFuture` instance is created and returned
in the resource method; the call to method `complete` on that instance
is executed only after the long running operation terminates.
