////
*******************************************************************
* Copyright (c) 2019 Eclipse Foundation
*
* This specification document is made available under the terms
* of the Eclipse Foundation Specification License v1.0, which is
* available at https://www.eclipse.org/legal/efsl.php.
*******************************************************************
////

[[runtimedelegate]]
== Runtime Delegate

`RuntimeDelegate` is an abstract factory class that provides various
methods for the creation of objects that implement JAX-RS APIs. These
methods are designed for use by other JAX-RS API classes and are not
intended to be called directly by applications. `RuntimeDelegate` allows
the standard JAX-RS API classes to use different JAX-RS implementations
without any code changes.

An implementation of JAX-RS MUST provide a concrete subclass of
`RuntimeDelegate`. Using the supplied `RuntimeDelegate` this can be
provided to JAX-RS in one of two ways:

1.  An instance of `RuntimeDelegate` can be instantiated and injected
using its static method `setInstance`. In this case the implementation
is responsible for creating the instance; this option is intended for
use with implementations based on IoC frameworks.
2.  The class to be used can be configured, see <<rdconfig>>. In
this case JAX-RS is responsible for instantiating an instance of the
class and the configured class MUST have a public constructor which
takes no arguments.

Note that an implementation MAY supply an alternate implementation of
the `RuntimeDelegate` API class (provided it passes the TCK signature
test and behaves according to the specification) that supports alternate
means of locating a concrete subclass.

A JAX-RS implementation may rely on a particular implementation of
`RuntimeDelegate` being used – applications SHOULD NOT override the
supplied `RuntimeDelegate` instance with an application-supplied
alternative and doing so may cause unexpected problems.

include::_rdconfig.adoc[]
