type=page
status=published
title=Executing Tests
next=debug.html
prev=config.html
~~~~~~
include::attributes.conf[]
Executing Tests
===============

[[GBFWO]]


[[executing-tests]]
5 Executing Tests
-----------------

The {TechnologyShortName} TCK uses the Junit and Jboss Arquillian 
frameworks to execute the tests.

This chapter includes the following topics:

* link:#GBFUZ[Starting the tests]
* link:#GBFWM[Running a Subset of the Tests]
* link:#GCLRR[Running the TCK Against your selected CI]
* link:#GCLRZ[Running the TCK Against a Vendor's Implementation]
* link:#GBFVK[Test Reports]


[NOTE]
=======================================================================

The instructions in this chapter assume that you have installed and
configured your test environment as described in
link:install.html#GBFTP[Chapter 3, "Installation,"] and
link:config.html#GBFVV[Chapter 4, "Setup and Configuration,"],
respectively.

=======================================================================

ifdef::rebuild[]
As explained in link:rebuild.html#GCLIZ[Appendix B, "Packaging the
Test Applications in Servlet-Compliant WAR
Files With VI-Specific Information,"] the {TechnologyShortName} TCK
introduces the concept of repackaging the TCK tests.
endif::rebuild[]

[NOTE]
=======================================================================

The Jakarta REST TCK is not depended on any particular build tool to 
run the tests. It will be convenient and advisable to create a 
Apache Maven project to setup and run the TCK. This chapter will 
henceforth use instructions and steps to provide setup with Apache 
Maven as a build tool.

=======================================================================



[[GBFUZ]][[starting-javatest]]

5.1 Starting the tests
~~~~~~~~~~~~~~~~~~~~~~

The {TechnologyShortName} TCK can be run from the command line 
in your shell environment by executing the TCK jar.


[NOTE]
=======================================================================

The `mvn` command referenced in the following
two procedures and elsewhere in this guide is the Apache Maven
build tool, which will need to be downloaded separately.

=======================================================================




[[GBFVW]][[to-start-javatest-in-command-line-mode]]

5.1.1 To Start Tests in Command-Line Mode
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

include::using-examples.inc[]

[[GBFWM]][[running-a-subset-of-the-tests]]

5.2 Running a Subset of the Tests
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Use the following modes to run a subset of the tests:

* link:#GBFWK[Section 5.2.1, "To Run a Subset of Tests in Command-Line Mode"]


[[GBFWK]][[to-run-a-subset-of-tests-in-command-line-mode]]

5.2.1 To Run a Subset of Tests in Command-Line Mode
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Start the test run by executing the following command: +

[source,subs="attributes"]
----
mvn verify -Dit.test={subsetTestDirectoryExample}.**
----

The tests in the directory and its subdirectories are run.

[NOTE]
=======================================================================

The Junit test tags(groups) available in the TCK are `xml_binding`, 
`security`, `servlet` and `se_bootstrap`. These can be used to select or 
deselect the tests for the execution. 

=======================================================================

[[GBFQA]][[to-run-a-group-of-tests-in-command-line-mode]]

5.2.2 To Run a Group of Tests in Command-Line Mode
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Start the test run by executing the following command: +

[source,subs="attributes"]
----
mvn verify -Dgroups={groupsExample}
----

Only the tests in the group +{groupsExample}+ is run. 
Multiple groups can be separated by comma.


[[GBFEP]][[to-exclude-a-group-of-tests-in-command-line-mode]]

5.2.3 To Exclude a Group of Tests in Command-Line Mode
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Start the test run by executing the following command: +

[source,subs="attributes"]
----
mvn verify -DexcludedGroups={groupsExample}
----

The tests in the group +{groupsExample}+ is exclued from the run. 
Multiple groups can be separated by comma.

[[GCLRR]][[running-the-tck-against-the-ri]]

5.3 Running the TCK Against another CI
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Some test scenarios are designed to ensure that the configuration and deployment of
all the prebuilt {TechnologyShortName} TCK tests against one Compatible
Implementation are successful operating with other compatible implementations, and that the TCK is ready for
compatibility testing against the Vendor and Compatible Implementations.

1.  Verify that you have followed the configuration instructions in
link:config.html#GBFVU[Section 4.1, "Configuring Your Environment to Run
the TCK Against the Compatible Implementation."]
2.  If required, verify that you have completed the steps in
link:config.html#GCLIW[Section 4.3.2, "Deploying the Prebuilt Archives."]
3.  Run the tests, as described in link:#GBFUZ[Section 5.1, "Starting
the tests,"] and, if desired, link:#GBFWM[Section 5.2, "Running a Subset
of the Tests."]

[[GCLRZ]][[running-the-tck-against-a-vendors-implementation]]

5.4 Running the TCK Against a Vendor's Implementation
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

This test scenario is one of the compatibility test phases that all
Vendors must pass.

1.  Verify that you have followed the configuration instructions in
link:config.html#GCLHU[Section 4.2, "Configuring Your Environment to
Repackage and Run the TCK Against the Vendor Implementation."]
2.  If required, verify that you have completed the steps in
link:config.html#GCLIL[Section 4.3.3, "Deploying the
Test Applications Against the Vendor Implementation."]
3.  Run the tests, as described in link:#GBFUZ[Section 5.1, "Starting
the tests,"] and, if desired, link:#GBFWM[Section 5.2, "Running a Subset
of the Tests."]

[[GBFVK]][[test-reports]]

5.5 Test Reports
~~~~~~~~~~~~~~~~

A set of report files is created for every test run. These report files
can be found in the target directory that the test is run. After a test run is
completed, the Junit framework writes  reports for the test run.
