////
*******************************************************************
* Copyright (c) 2019 Eclipse Foundation
*
* This specification document is made available under the terms
* of the Eclipse Foundation Specification License v1.0, which is
* available at https://www.eclipse.org/legal/efsl.php.
*******************************************************************
////

[[determine_response_type]]
=== Determining the MediaType of Responses

In many cases it is not possible to statically determine the media type
of a response. The following algorithm is used to determine the response
media type, latexmath:[$M_{\mbox{selected}}$], at run time:

1.  If the method returns an instance of `Response` whose metadata
includes the response media type (latexmath:[$M_{\mbox{specified}}$])
then set latexmath:[$M_{\mbox{selected}} = M_{\mbox{specified}}$],
finish.
2.  Gather the set of producible media types latexmath:[$P$]:
* If the method is annotated with `@Produces`, set
latexmath:[$P = \{ V(\mbox{method}) \}$] where latexmath:[$V(t)$]
represents the values of `@Produces` on the specified target
latexmath:[$t$].
* Else if the class is annotated with `@Produces`, set
latexmath:[$P = \{ V(\mbox{class}) \}$].
* Else set latexmath:[$P = \{ V(\mbox{writers}) \}$] where writers is
the set of `MessageBodyWriter` that support the class of the returned
entity object.
3.  If latexmath:[$P = \{\}$], set
latexmath:[$P = \{\mbox{\lq*/*\rq}\}$]
4.  Obtain the acceptable media types latexmath:[$A$]. If
latexmath:[$A = \{\}$], set latexmath:[$A = \{\mbox{\lq*/*\rq}\}$]
5.  Set latexmath:[$M=\{\}$]. For each member of latexmath:[$A, a$]:
* For each member of latexmath:[$P, p$]:
** If latexmath:[$a$] is compatible with latexmath:[$p$], add
latexmath:[$S(a,p)$] to latexmath:[$M$], where the function
latexmath:[$S$] returns the most specific media type of the pair with
the q-value of latexmath:[$a$] and server-side qs-value of
latexmath:[$p$].
6.  If latexmath:[$M = \{\}$] then generate a `NotAcceptableException`
(406 status) and no entity. The exception MUST be processed as described
in <<method_exc>>. Finish.
7.  Sort latexmath:[$M$] in descending order, with a primary key of
specificity (latexmath:[$\mbox{n/m} > \mbox{n/*} > \mbox{*/*}$]), a
secondary key of q-value and a tertiary key of qs-value.
8.  For each member of latexmath:[$M, m$]:
* If latexmath:[$m$] is a concrete type, set
latexmath:[$M_{\mbox{selected}} = m$], finish.
9.  If latexmath:[$M$] contains /* or application/*, set
latexmath:[$M_{\mbox{selected}} = \mbox{\lq application/octet-stream\rq}$],
finish.
10. Generate a `NotAcceptableException` (406 status) and no entity. The
exception MUST be processed as described in <<method_exc>>.
Finish.

Note that the above renders a response with a default media type of
application/octet-stream when a concrete type cannot be determined. It
is RECOMMENDED that `MessageBodyWriter` implementations specify at least
one concrete type via `@Produces`.
