////
*******************************************************************
* Copyright (c) 2019 Eclipse Foundation
*
* This specification document is made available under the terms
* of the Eclipse Foundation Specification License v1.0, which is
* available at https://www.eclipse.org/legal/efsl.php.
*******************************************************************
////

[[mapping_requests_to_java_methods]]
=== Matching Requests to Resource Methods

This section describes how a request is matched to a resource class and
method. Implementations are not required to use the algorithm as written
but MUST produce results equivalent to those produced by the algorithm.

[[reqpreproc]]
==== Request Preprocessing

Prior to matching, request URIs are normalizedfootnote:[Note: some
containers might perform this functionality prior to passing the request
to an implementation.] by following the rules for case, path segment,
and percent encoding normalization described in section 6.2.2 of RFC
3986<<bib5>>. The normalized request
URI MUST be reflected in the URIs obtained from an injected `UriInfo`.

[[request_matching]]
==== Request Matching

A request is matched to the corresponding resource method or
sub-resource method by comparing the normalized request URI (see
<<reqpreproc>>), the media type of any request entity, and the requested
response entity format to the metadata annotations on the resource
classes and their methods. If no matching resource method or
sub-resource method can be found then an appropriate error response is
returned. All exceptions reported by this algorithm MUST be processed as
described in <<method_exc>>.

Matching of requests to resource methods proceeds in three stages as
follows:

1.  Identify a set of candidate root resource classes matching the
request:
+
Input::
  latexmath:[$U=\mbox{request URI path},C=\{\mbox{root resource classes}\}$]
Output::
  latexmath:[$U=\mbox{final capturing group not yet matched}, C'=\{\mbox{root resouce classes matched so far}\}$]
    a.  Set latexmath:[$E=\{\}$].
    b.  For each class latexmath:[$Z$] in latexmath:[$C$] add a regular
expression (computed using the function latexmath:[$R(A)$] described in
<<template_to_regex>>) to latexmath:[$E$] as follows:
* Add latexmath:[$R(T_Z)$] where latexmath:[$T_Z$] is the URI
path template specified for the class latexmath:[$Z$].
+
Note that two or more classes in latexmath:[$C$] may add the same
regular expression to latexmath:[$E$] if they are annotated with the
same URI path template (modulo variable names).
    c.  Filter latexmath:[$E$] by matching each member against
latexmath:[$U$] as follows:
* Remove members that do not match latexmath:[$U$].
* Remove members for which the final regular expression capturing group
(henceforth simply referred to as a capturing group) value is neither
empty nor / and the class latexmath:[$Z$] has no sub-resource methods or
locators.
    d.  If latexmath:[$E$] is empty then no matching resource can be found,
the algorithm terminates and an implementation MUST generate a
`NotFoundException` (404 status) and no entity.
    e.  Sort latexmath:[$E$] using the number of literal
charactersfootnote:[Here, literal characters means those not resulting
from template variable substitution.] in each member as the primary key
(descending order), the number of capturing groups as a secondary key
(descending order) and the number of capturing groups with non-default
regular expressions (i.e. not ([ /]+?)) as the tertiary key (descending
order).
    f.  Set latexmath:[$R_{\mbox{match}}$] to be the first member of
latexmath:[$E$] and set latexmath:[$U$] to be the value of the final
capturing group of latexmath:[$R_{\mbox{match}}$] when matched against
latexmath:[$U$]. Let latexmath:[$C'$] be the set of classes
latexmath:[$Z$] such that latexmath:[$R(T_Z)=R_{\mbox{match}}$]. By
definition, all root resource classes in latexmath:[$C'$] must be
annotated with the same URI path template modulo variable names.
2.  Obtain a set of candidate resource methods for the
request:
+
Input::
  latexmath:[$U=\mbox{final capturing group not yet matched}, C'=\{\mbox{root resouce classes matched so far}\}$]
Output::
  latexmath:[$M=\{\mbox{candidate resource methods}$]}
    a.  [check_null] If latexmath:[$U$] is null or /, set
latexmath:[\[M = \{\mbox{resource methods of all classes in $C'$ (excluding sub-resource methods)}\}\]]
and go to step [find_method] if latexmath:[$M \neq \{\}$]
    b.  Set latexmath:[$E=\{\}$].
    c.  For each class latexmath:[$Z'$] in latexmath:[$C'$] add regular
expressions to latexmath:[$E$] for each sub-resource method and locator
as follows:
        i) For each sub-resource method latexmath:[$D$], add
latexmath:[$R(T_D)$] where latexmath:[$T_D$] is the URI path template of
the sub-resource method.
        ii) For each sub-resource locator latexmath:[$L$], add
latexmath:[$R(T_L)$] where latexmath:[$T_L$] is the URI path template of
the sub-resource locator.
    d.  Filter latexmath:[$E$] by matching each member against
latexmath:[$U$] as follows:
* Remove members that do not match latexmath:[$U$].
* Remove members derived from latexmath:[$T_D$] (those added in step
[t_method_items]) for which the final capturing group value is neither
empty nor /.
    e.  If latexmath:[$E$] is empty, then no matching resource can be found
and the algorithm terminates by generating a `NotFoundException` (404
status) and no entity.
    f.  Sort latexmath:[$E$] using the number of literal characters in each
member as the primary key (descending order), the number of capturing
groups as a secondary key (descending order), the number of capturing
groups with non-default regular expressions (i.e. not ([ /]+?)) as the
tertiary key (descending order), and the source of each member as
quaternary key sorting those derived from sub-resource methods ahead of
those derived from sub-resource locators.
    g.  Set latexmath:[$R_{\mbox{match}}$] to be the first member of
latexmath:[$E$]
    h.  Set latexmath:[$M$] as follows,
latexmath:[M = \{\mbox{subresource methods of all classes in $C'$ (excluding sub-resource locators)}\}\]]
and go to step 3 if latexmath:[$M \neq \{\}$].
    i.  Let latexmath:[$L$] be a sub-resource locator such that
latexmath:[$R_{\mbox{match}} = R(T_L)$]. Implementations SHOULD report
an error if there is more than one sub-resource locator that satisfies
this condition. Set latexmath:[$U$] to be the value of the final
capturing group of latexmath:[$R(T_L)$] when matched against
latexmath:[$U$], and set latexmath:[$C'$] to be the singleton set
containing only the class that defines latexmath:[$L$].
    j. Go to step 2a.
3.  Identify the method that will handle the request:
+
Input::
  latexmath:[$M=\mbox{candidate resource methods}$]
Output::
  latexmath:[$O=\mbox{instance of resource class matched}, D=\mbox{resource method matched from $M$}$]
    a.  Filter latexmath:[$M$] by removing members that do
not meet the following criteria:
* The request method is supported. If no methods support the request
method an implementation MUST generate a `NotAllowedException` (405
status) and no entity. Note the additional support for `HEAD` and
`OPTIONS` described in Section [head_and_options].
* The media type of the request entity body (if any) is a supported
input data format (see Section [declaring_method_capabilities]). If no
methods support the media type of the request entity body an
implementation MUST generate a `NotSupportedException` (415 status) and
no entity.
* At least one of the acceptable response entity body media types is a
supported output data format (see Section
[declaring_method_capabilities]). If no methods support one of the
acceptable response entity body media types an implementation MUST
generate a `NotAcceptableException` (406 status) and no entity.
    b.  If after filtering the set latexmath:[$M$] has more than one
element, sort it in descending order as follows. First, let us define
the _client_ media type and the _server_ media type as those denoted by
the `Accept` header in a request and the `@Produces` annotation on a
resource method, respectively. Let a client media type be of the form
latexmath:[$\mbox{$n$/$m$;q=$v_1$}$], a server media type be of the form
latexmath:[$\mbox{$n$/$m$;qs=$v_2$}$] and a _combined_ media type of the
form latexmath:[$\mbox{$n$/$m$;q=$v_1$;qs=$v_2$;d=$v_3$}$], where the
distance factor latexmath:[$d$] is defined below. For any of these
types, latexmath:[$m$] could be latexmath:[$*$], or latexmath:[$m$] and
latexmath:[$n$] could be latexmath:[$*$] and the values of q and qs are
assumed to be latexmath:[$1.0$] if absent.
+
Let latexmath:[$S(p_1, p_2)$] be defined over a client media type
latexmath:[$p_1$] and a server media type latexmath:[$p_2$] as the
function that returns the _most_ specific combined type with a distance
factor if latexmath:[$p_1$] and latexmath:[$p_2$] are compatible and
latexmath:[${\perp}$] otherwise. For example:
* latexmath:[$S(\mbox{text/html;q=1}, \mbox{text/html;qs=1}) = \mbox{text/html;q=1;qs=1;d=0}$],
* latexmath:[$S(\mbox{text/*;q=0.5}, \mbox{text/html;qs=0.8}) = \mbox{text/html;q=0.5;qs=0.8;d=1}$],
* latexmath:[$S(\mbox{*/*;q=0.2}, \mbox{text/*;qs=0.9}) = \mbox{text/*;q=0.2;qs=0.9;d=1}$],
* latexmath:[$S(\mbox{text/*;q=0.4}, \mbox{application/*;qs=0.3}) = {\perp}$].
+
where the latexmath:[$d$] factor corresponds to the number of wildcards
matched with a concrete type or subtype. Note that q and qs are not
matched, but simply combined in the resulting media type. A total
ordering can be defined over combined media types as follows.
+
We write
latexmath:[$\mbox{$n_1$/$m_1$;q=$v_1$;qs=$v_1'$;d=$v_1''$} \ge \mbox{$n_2$/$m_2$;q=$v_2$;qs=$v_2'$;d=$v_2''$}$]
if one of these ordered conditions holds:
i)  latexmath:[$\mbox{$n_1$/$m_1$} \succ \mbox{$n_2$/$m_2$}$] where the
partial order latexmath:[$\succ$] is defined as
latexmath:[$\mbox{$n$/$m$} \succ \mbox{$n$/*} \succ \mbox{*/*}$],
ii)  latexmath:[$\mbox{$n_2$/$m_2$} \nsucc \mbox{$n_1$/$m_1$}$] and
latexmath:[$v_1 > v_2$],
iii)  latexmath:[$\mbox{$n_2$/$m_2$} \nsucc \mbox{$n_1$/$m_1$}$] and
latexmath:[$v_1 = v_2$] and latexmath:[$v_1' > v_2'$].
iv)  latexmath:[$\mbox{$n_2$/$m_2$} \nsucc \mbox{$n_1$/$m_1$}$] and
latexmath:[$v_1 = v_2$] and latexmath:[$v_1' = v_2'$] and
latexmath:[$v_1'' \le v_2''$].
+
Note that latexmath:[$\ge$] is a total order even though
latexmath:[$\succ$] is a partial order. For example, the following holds
latexmath:[$\mbox{text/html;q=1.0;qs=0.7;d=0} \ge \mbox{application/xml;q=1.0;qs=0.2;d=0}$]
even though latexmath:[$\mbox{text/html}$] is incomparable to
latexmath:[$\mbox{application/xml}$] according to latexmath:[$\succ$].
Additionally, it is possible under latexmath:[$\ge$] for two types to be
equal even though they are not identical footnote:[E.g.,
latexmath:[$\mbox{text/html;q=1.0;qs=0.7;d=0} \ge \mbox{application/xml;q=1.0;qs=0.7;d=0}$]
and
latexmath:[$\mbox{application/xml;q=1.0;qs=0.7;d=0} \ge \mbox{text/html;q=1.0;qs=0.7;d=0}$].].
For convenience, we defined latexmath:[$p \ge {\perp}$] for every media
type latexmath:[$p$].
+
Given these definitions, we can now sort latexmath:[$M$] in descending
order based on latexmath:[$\ge$] as followsfootnote:[If any of these
types or sets of types are unspecified, latexmath:[$\mbox{*/*}$] and
latexmath:[$\mbox{\{*/*\}}$] are assumed.]:
* Let latexmath:[$t$] be the request content type and latexmath:[$C_M$]
a resource method’s `@Consumes` set of server media types, we use the
media type
latexmath:[$\max_\ge \{ S(t,c)  \, | \, (t, c) \in \{t\} \times C_M\}$]
as primary key.
* Let latexmath:[$A$] be the request accept header set of client media
types and latexmath:[$P_M$] a resource method’s `@Produces` set of
server media types, we use the media type
latexmath:[$\max_\ge \{ S(a,p) \, | \, (a,p) \in A \times P_M\}$] as
secondary key. If there is more than one maximum element ,
implementations SHOULD report a warning and select one of these types in
an implementation dependent manner.
c.  Let latexmath:[$D$] be the first resource method
in the set latexmath:[$M$]footnote:[Step [filter_methods] ensures the
set contains at least one member.] and latexmath:[$O$] an instance of
the class that defines latexmath:[$D$]. If after sorting, there is more
than one maximum element in latexmath:[$M$], implementations SHOULD
report a warning and select one of these methods in an implementation
dependent manner.
+
Consider the following example and assume the request to be `GET`
`widgets/1`:
+
[source,java]
----
@Path("widget")
public class WidgetResource {
    private String id;

    public WidgetResource() {
        this("0");
    }

    public WidgetResource(String id) {
        this.id = id;
    }

    @GET
    public Widget findWidget() {
        return Widget.findWidgetById(id);
    }
}

@Path("widgets")
public class WidgetsResource {

    @Path("{id}")
    public WidgetResource getWidget(@PathParam("id") String id) {
        return new WidgetResource(id);
    }
}
----
+
The input and output values for each of the 3 steps in the matching
algorithm are as follows:
+
Step 1::
  Identify a set of candidate root resource classes matching the
  request. Let latexmath:[$R(\mbox{widgets}) = \mbox{widgets(/.*)?}$]
  and latexmath:[$R(\mbox{widget}) = \mbox{widget(/.*)?}$],
  +
  Input;;
    latexmath:[$U = \mbox{widgets/1}$] and
    latexmath:[$C = \{\mbox{WidgetResource}, \mbox{WidgetsResource}\}$]
  Output;;
    latexmath:[$U = \mbox{/1}$] and
    latexmath:[$C' = \{\mbox{WidgetsResource}\}$]
Step 2::
  Obtain a set of candidate resource methods for the request. Let
  latexmath:[$R(\{\mbox{id}\}) = \mbox{([\^{ }/]+?)(/.*)?}$],
  +
  Input;;
    latexmath:[$U = \mbox{/1}$] and
    latexmath:[$C' = \{\mbox{WidgetsResource}\}$]
  Output;;
    latexmath:[$M = \{\mbox{findWidget}\}$]
Step 3::
  Identify the method that will handle the request,
  +
  Input;;
    latexmath:[$M = \{\mbox{findWidget}\}$]
  Output;;
    latexmath:[$O = \mbox{WidgetResource instance}$] and
    latexmath:[$D = \mbox{findWidget}$]
+
Note that the algorithm matches a single root resource class
(WidgetsResource) and, consequently, the `@Path` annotation on
WidgetResource is ignored for the request `GET` `widgets/1`.

[[template_to_regex]]
==== Converting URI Templates to Regular Expressions

The function latexmath:[$R(A)$] converts a URI path template annotation
latexmath:[$A$] into a regular expression as follows:

1.  URI encode the template, ignoring URI template variable
specifications.
2.  Escape any regular expression characters in the URI template, again
ignoring URI template variable specifications.
3.  Replace each URI template variable with a capturing group containing
the specified regular expression or ([ /]+?) if no regular expression is
specifiedfootnote:[Note that the syntax +? denotes a reluctant
quantifier as defined in the java.util.regex.Pattern class.].
4.  If the resulting string ends with / then remove the final character.
5.  Append (/.*)? to the result.

Note that the above renders the name of template variables irrelevant
for template matching purposes. However, implementations will need to
retain template variable names in order to facilitate the extraction of
template variable values via `@PathParam` or
`UriInfo.getPathParameters`.
